name: Build docker image to test
on:
  push:
    branches-ignore:
      - main
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        file: ./ubuntu-noble.docker
        push: false

